### ISSUE TITLE
org.gephi:gephi-maven-plugin:generate doesn't generate correct manifest.mf

### ISSUE THREAD

**Issue by totetmatt** [gephi/gephi-maven-plugin#1]
After using _org.gephi:gephi-maven-plugin:generate_, the Module Manifest 

```
gephi-plugins\modules\MyModule\src\main\nbm\manifest.mf
```

Doesn't contain the following parameters even if they are fill up during the _generate_ process:
- OpenIDE-Module-Short-Description
- OpenIDE-Module-Long-Description

Which result in an error during compilation

**Comment by mbastian** [comment]
Arg, I broke something
