### ISSUE TITLE
Maven error in generated pom.xml file

### ISSUE THREAD

**Issue by BoiseStateCS410** [gephi/gephi-maven-plugin#11]
Ran the Generate script which produced the expected pom.xml file for the target module.
The generated build section plugin is flagged with this error:

"Plugin execution not covered by lifecycle configuration: org.apache.netbeans.utilities:nbm-maven-plugin:4.5:manifest (execution: default-manifest, phase: process-classes)"

Running on Eclipse 4.22 on win 11 maven m2e v 1.19.0 w java 14.

What can I do to resolve this error message?
Thanks

(I renamed the pom.xml to pom.txt because this page wouldn't let me attach an XML file.)

[pom.txt](https://github.com/gephi/gephi-maven-plugin/files/8567610/pom.txt)
.

**Comment by mbastian** [comment]
Hi, I replied to you [here](https://github.com/gephi/gephi-plugins/issues/248). Please don't create multiple duplicate issues.
