### ISSUE TITLE
How to develop multiple, independent plugins

### ISSUE THREAD

**Issue by jbliesener** [gephi/gephi-maven-plugin#9]
Hello,

I'm working on a set of plugins, each independent from the others. One of them is a statistics module that I think is of general interes and I'd like to publish on the Plugins Marketplace. Another one is a layout plugin.

While I can define and compile several plugins in my gephi-plugins folder, I seem to be unable to run Gephi if those plugis are independent from each other. The error message I get is: 

> Multiple module suites have been found, this is not supported

This was possible in Gephi 0.8.2 with the former Ant build process.

So, here's my question: How can I author several independent plugins (having different licenses) and run them all together in a single Gephi 0.9.1.x instance?

**Comment by eduramiba** [comment]
Hi,
You should create a separate git branch for each of your plugins.

If you want to test several plugins at the same time before they are published, I think your best option is to run Gephi and manually install the .nbm files that each of your plugin produces when you run `mvn install` (they will be under `target` folder of your module).

**Comment by jbliesener** [comment]
Thank you, Eduardo. I'll go that way.

**Comment by eduramiba** [comment]
Great :) When you want to publish your plugins, remember to create a separate pull-request to master-forge branch for each plugin.
